name: .NET Core build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: InferSharp
      uses: microsoft/infersharpaction@v0.2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with: 
        dotnet-version: 6.0.x 
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: IoTSharp/ClientApp/package-lock.json
    - name: Build
      run: dotnet build  ./IoTSharp.sln  --configuration Release 

      
      
